### ISSUE TITLE
[Bug] 一些bug反馈

### ISSUE THREAD

**Issue by CommonMuJi** [TartaricAcid/YSM-Netease-Plugins#1]
简单测了一下 目前存在以下问题
1.左右手道具位点没有转化出来
2.左右手的挥动动画在配置文件里是righthand这种命名，而动画文件里是mainhand这种命名，导致测试时读取不到相关动画
3.riptide动画没转化出来
4.轮盘动画只能转换出0-7的转盘动画，额外的动画没有转换
5.在parallel或pre-parallel的动画兼容有问题，例如我在preparallel给一个组缩放为0，在转盘动画使这个组缩放为1，在正常情况下该组的缩放应该为1，而现在的情况是他的缩放为0
6.molang函数不能正常调用，例如我在parallel里定义一个组缩放为1-v.roaming.a，正常情况下不改变该系数数值默认应该显示这个组的缩放为1，而实际展示的却是该组的缩放为0

**Comment by TartaricAcid** [comment]
1. 左右手需要手动改名，修改为 `leftItem` 和 `rightItem`，这块后续会做成插件自动转换的功能
2. 没看懂
3. 网易版没有这个动画，这个在 Java 版是使用了三叉戟的激流后才会播放的动画。
4. 这个是插件 bug，后续修
5. ~~那个叫 `轮盘动画`~~，你的这个轮盘动画是否勾选了“覆盖”选项？如果没有勾选，无法覆盖并行动画。
6. 基岩版的 molang 功能很羸弱，并且和 Blockbench 的行为可能有不一致的地方，赋值和计算语句必须放在 timeline（也就是 Blockbench 翻译叫做`效果-指令`那一栏），并不能随意在任何地方放，否则无法计算赋值。你可能需要自行修改相应 molang

**Comment by CommonMuJi** [comment]
2的意思是use_righthand这一系列就没转化出来 因为转化前的名称是这个
![VZ 0%7OPE9KMZ9WQWU9$ NP](https://github.com/user-attachments/assets/1f2097f1-0039-449f-be4d-59bfe4172280)
所以可能是某些地方写错了？

**Comment by TartaricAcid** [comment]
你目前反馈的所有问题已经全部解决，请使用最新版插件
