### ISSUE TITLE
基于V1.0.8的更多bug反馈

### ISSUE THREAD

**Issue by CommonMuJi** [TartaricAcid/YSM-Netease-Plugins#2]
![@GJAP%B33{73 Z(C5$F5UL](https://github.com/user-attachments/assets/22248c7c-fec9-46ac-86ca-8e07cadf5c0a)
头发，胸部相关molang函数转化出来持续报错

**Comment by TartaricAcid** [comment]
你这得发一下测试的模型，我没法通过这一段判断问题出在哪

**Comment by CommonMuJi** [comment]
> 你这得发一下测试的模型，我没法通过这一段判断问题出在哪

[test_winefox.zip](https://github.com/user-attachments/files/18162102/test_winefox.zip)
![3B5(34{I0`0METXH_0 Y5N](https://github.com/user-attachments/assets/1eaa927c-4372-4227-99e0-b81cf852542b)
我尝试用默认模型进行了转换 问题是一致的，是原本的适用于java版的物理相关molang函数不适配网易却没有删除导致测试时相关函数持续报错？

**Comment by TartaricAcid** [comment]
但是游戏内确实没发现什么问题，先这样，后续看看具体是什么原因

**Comment by TartaricAcid** [comment]
已经彻底解决，问题为 GUI 动画中使用了 molang 变量

1.1.0 版本插件已经能够删除所有的 GUI 动画 molang 变量
